pathways:
  default: workshop

  paths:
    workshop:
      title: "Workshop"

      steps:
      - 00-workshop-overview
      - 01-install
      - 02-first-steps
      - 03-patching
      - 04-first-upgrade-steps
      - 05-spring-boot-upgrades
      - 06-accelerating-upgrades
      - 07-openrewrite-recipes
      - 08-custom-mappings
      - 09-spring-boot-4
      - 10-continuous-upgrades
      - 99-workshop-summary
