pathways:
  default: workshop

  paths:
    workshop:
      title: "Workshop"

      steps:
      - 00-workshop-overview
      - 01-install
      - 02-first-steps
      - 03-first-upgrade-steps
      - 04-spring-boot-upgrades
      - 05-accelerating-upgrades
      - 06-openrewrite-recipes
      - 07-custom-mappings
      - 08-spring-boot-4
      - 09-continuous-upgrades
      - 99-workshop-summary
