apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spring-enterprise-guides-advisor-install
spec:
  title: Spring Academy - Enterprise Guides - App Advisor Install
  description: Install and use App Advisor in a standalone fashion
  difficulty: beginner
  duration: 30m
  vendor: Broadcom
  workshop:
    image: jdk17-environment:*
    files:
      - http:
          # the name of the tar.gz here should make the workshop name
          url: "$(ingress_protocol)://$(workshop_namespace)-files.$(ingress_domain)/spring-enterprise-guides-advisor-install.tar.gz"
        #includePaths:
        #- /workshop/**
        #- /exercises/**
        #- /README.md
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    namespaces:
      security:
        token:
          # This wasn't being done before but should be so that workshop user
          # cannot access the Educates cluster session namespace, which they don't need.
          # See note below though about volume mount for token.
          enabled: false
    env:
    - name: LAB_NUMBER
      value: "2"
    - name: WEBSERVER
      value: "$(ingress_protocol)://$(workshop_namespace)-files.$(ingress_domain)"
    - name: BOOTSTRAP_COMMAND
      value: ":"
    applications:
      terminal:
        enabled: true
      editor:
        enabled: true
      git:
        enabled: true
    volumes:
    - name: workshop-init-container-scripts
      secret:
        secretName: workshop-init-container-scripts
        defaultMode: 0755
    patches:
      initContainers:
      - name: tap-sandbox-setup
        # Educates needs a $(base_environment_image) variable can use.
        # For now hard wire to educates-base-environment image. Aim to
        # change for Educates 2.6.0.
        image: ghcr.io/vmware-tanzu-labs/educates-base-environment:2.5.2
        # Execute setup script mounted from secret.
        command: ["/opt/init-setup-scripts/setup.sh"]
        volumeMounts:
        - name: workshop-init-container-scripts
          mountPath: /opt/init-setup-scripts
  environment:
    objects:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: workshop-init-container-scripts
      stringData:
        setup.sh: |
          #!/bin/bash
          set -x
          set -eo pipefail
          echo "Put commands here that need to be done in init container prior to workshop session"
    - apiVersion: v1
      kind: Service
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        type: ClusterIP
        ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
        selector:
          deployment: files
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        tls:
        - hosts:
            - $(workshop_namespace)-files.$(ingress_domain)
          secretName: $(ingress_secret)
        rules:
        - host: $(workshop_namespace)-files.$(ingress_domain)
          http:
            paths:
            - backend:
                service:
                  name: $(workshop_namespace)-files
                  port:
                    number: 80
              pathType: Prefix
              path: /
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        serviceAccountName: $(service_account)
        replicas: 1
        selector:
          matchLabels:
            deployment: files
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: files
          spec:
            containers:
            - name: files
              image: ghcr.io/spring-academy/spring-enterprise-guides:${VERSION}