[program:enterprise-spring-repo-server]
process_name=enterprise-spring-repo-server
directory=/opt/application-advisor
command=/usr/bin/python3 -m http.server 9000
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true
autorestart=true