name: "Deploy to Production"
run-name: Deploy Content and Metadata from ${{ github.ref_name }} to Production
concurrency: deploy-production

on:
  # push:
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  deployment:
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make Image for Environment
        run: |
          make deploy-lab version=${{ github.ref_name }} environment=prod
      - name: Deploy to EMMIT
        env:
          PENGUINCTL_APIURL: ${{ secrets.PENGUINCTL_APIURL_PROD }}
          PENGUINCTL_APITOKEN: ${{ secrets.PENGUINCTL_APITOKEN_PROD }}
        run: |
          make deploy-lms
