name: "Deploy to Staging"
run-name: Deploy Content and Metadata from ${{ github.ref_name }} to Staging
concurrency: deploy-staging

on:
  workflow_dispatch:

jobs:
  deployment:
    name: Deploy to Staging
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make Image for Environment
        run: |
          make deploy-lab version=${{ github.ref_name }} environment=staging
      - name: Deploy to EMMIT
        env:
          PENGUINCTL_APIURL: ${{ secrets.PENGUINCTL_APIURL_STAGING }}
          PENGUINCTL_APITOKEN: ${{ secrets.PENGUINCTL_APITOKEN_STAGING }}
        run: |
          make deploy-lms
